### ISSUE TITLE
about struct a

### ISSUE THREAD

**Issue by tpunix** [zecoxao/vita-parsedreg#1]
The struct a should be this:
struct category_t {
	int system_magic; /* opend registry struct address in memory */
	short parent;
	short hash_id;	/* (hash%total_categorys) */
	short hash;
	short nent;
	short nblk;
	char name[28];
	short unused;
	unsigned short fat[7];
};

**Comment by zecoxao** [comment]
thanks! can you make a PR with the necessary changes?

**Comment by zecoxao** [comment]
done, closing...
